Setup the python environment with conda and create a minimal scraper
tsdataclinic/gtfs-realtime-capsule pull request #6
Opened 2024-08-16 14:26 UTC by AndiLi99

2024-08-16 16:31 UTC, kaushik12 requested changes
Can you add a folder structure
`/data`  for any raw/sample data we push
`/src/...` where we can further group the code into scraper/normalizer/compactor (for example)

2024-08-18 21:37 UTC, AndiLi99 commented
> Can you add a folder structure `/data` for any raw/sample data we push `/src/...` where we can further group the code into scraper/normalizer/compactor (for example)

Added the folder structure!

2024-08-19 15:09 UTC, kaushik12 approved these changes

2024-08-19 15:12 UTC, kaushik12 commented
Closes #8

2024-08-19 15:12 UTC, merged